### ISSUE TITLE
No such file or directory: .vscode-server/bin/ ... /bin/code

### ISSUE THREAD

**Issue by sebastian-ruiz** [chvolkmann/code-connect#12]
I am getting the following error:

```
➜ code .
Traceback (most recent call last):
  File "/home/sruiz/.code-connect/bin/code_connect.py", line 121, in <module>
    main()
  File "/home/sruiz/.code-connect/bin/code_connect.py", line 114, in main
    proc = sp.run(args)
  File "/home/sruiz/anaconda3/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/sruiz/anaconda3/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/sruiz/anaconda3/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/sruiz/.vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/bin/code'
```
and
```
➜ ls .vscode-server/bin/c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5/bin
code-server  helpers  remote-cli
```
For some reason `code` is missing?

I have vscode running and connected to the server that I am SSH'ed into.

**Comment by sebastian-ruiz** [comment]
Oh this is fixed in pull-request #11
